Crdt demo
sillsdev/languageforge-lexbox pull request #1053
Opened 2024-09-11 19:30 UTC by hahn-kev

features

- upload project to server

2024-09-24 17:46 UTC, myieye requested changes
This is just a partial review sadly.
I'll try to finish tomorrow.
I'm posting it to make my progress official 😉.

2024-09-25 02:56 UTC, hahn-kev commented on backend/FwLite/LocalWebApp/Routes/AuthRoutes.cs
> +                var result = await factory.GetHelper(options.Value.GetServerByAuthority(server)).SignIn();
good catch, it was a left over from the previous name

2024-09-25 02:57 UTC, hahn-kev commented on backend/FwLite/LocalWebApp/Hubs/CrdtMiniLcmApiHub.cs
> +        Context.Items["clanup"] = cleanup;
nice catch, I refactored this a bit

2024-09-25 03:04 UTC, hahn-kev commented on backend/FwLite/FwLiteDesktop/MainPage.xaml.cs
> +        webView.IsVisible = false;
yeah I think it was left over from when I was troubleshooting something else

2024-09-25 03:35 UTC, hahn-kev commented on backend/FwLite/LocalWebApp/Hubs/CrdtMiniLcmApiHub.cs
> +            //todo this results in a memory leak, due to holding on to the hub instance, it will be disposed even if the context items are not.
I can't remember why I put that comment there, and I don't think it's valid. I also actually debugged the application and it doesn't look like there's a leak there, so I'm not worried.

2024-09-25 04:09 UTC, hahn-kev commented on backend/FwLite/LocalWebApp/Hubs/CrdtMiniLcmApiHub.cs
> +        return base.SearchEntries(query, options);
good thinking, I've written some tests for it, it's not exhaustive but it should get the job done

2024-09-25 14:04 UTC, myieye approved these changes
Mostly LGTM 😎 

I added 2 tiny commits as I found small UI bugs and such...maybe I should have put them in my own PR.

2024-09-26 09:02 UTC, hahn-kev commented on backend/FwLite/FwLiteDesktop/MainPage.xaml.cs
> +        //not currently working
haha yeah it's no longer valid

2024-10-02 02:18 UTC, merged