Complex forms and components UI
sillsdev/languageforge-lexbox pull request #1121
Opened 2024-10-11 15:11 UTC by myieye

![image](https://github.com/user-attachments/assets/07f3ae60-b7b0-4319-8c0b-a8348405f574)
![image](https://github.com/user-attachments/assets/2e24ed25-34a3-4556-9045-af569f007d63)
![image](https://github.com/user-attachments/assets/91cbb7e6-2b41-4c3b-be60-82f4f3c7b072)

2024-10-15 09:07 UTC, hahn-kev requested changes
I made some changes as I went, feel free to adjust any of them as needed. I left 2 questions/comments.

2024-10-15 09:43 UTC, myieye commented on frontend/viewer/src/lib/entry-editor/EntryOrSensePicker.svelte
> +                // the change event above is not in use, so we need to do it here
The comment is valid in the context of the `if` it's inside.

2024-10-15 09:45 UTC, myieye commented on frontend/viewer/src/lib/entry-editor/EntryOrSensePicker.svelte
> +                // the change event above is not in use, so we need to do it here
Actually, only this part: `if (disableExpand)`.
The `disabledEntry` part should probably just set the disabled attribute of the button it's on.

2024-10-15 09:46 UTC, myieye commented on frontend/viewer/src/lib/entry-editor/field-editors/ComplexFormTypes.svelte
> +        <!-- TODO: implement form type picker or dropdown? <EntryOrSensePicker title="Add complex form" bind:open={openPicker} noSenses on:pick={(e) => addComplexFormType(e.detail)} /> -->
Yeah, I'd like to do that in a follow up PR.

2024-10-16 05:09 UTC, hahn-kev commented on frontend/viewer/src/lib/entry-editor/EntryOrSensePicker.svelte
> +                // the change event above is not in use, so we need to do it here
I'm not sure I understand. By `change event` are you referring to this `on:click` handler?

2024-10-16 06:58 UTC, myieye commented on frontend/viewer/src/lib/entry-editor/EntryOrSensePicker.svelte
> +                // the change event above is not in use, so we need to do it here
I clarified the comment and did a tiny refactor 29446191bf06a2b73388378ada1427bb96e84bc4

2024-10-17 03:27 UTC, hahn-kev approved these changes

2024-10-17 06:13 UTC, merged