Fix org sorting
sillsdev/languageforge-lexbox pull request #1183
Opened 2024-10-30 13:13 UTC by myieye

This PR adds **THEN sort by name ASC**.
So, the sort order isn't random e.g. when sorting by member count and there are multiple orgs with 5 members.

2024-11-01 03:43 UTC, hahn-kev reviewed
what if we used a zero dependency order by lib to do this for us?
https://www.npmjs.com/package/just-order-by

2024-11-04 03:55 UTC, hahn-kev requested changes
see above comment

2024-11-04 09:35 UTC, myieye commented
> what if we used a zero dependency order by lib to do this for us? https://www.npmjs.com/package/just-order-by

I like that idea. Those "just" packages sound like a decent choice.
I'd never really looked beyond lodash. I probably should have used something for my debounce stuff and there's some viewer code that really wants a throttle, but I didn't want to write it. I should have just pulled in a small dependency.

I'd be tempted to go with [es-toolkit](https://www.reddit.com/r/javascript/comments/1dvmd1v/estoolkit_a_23x_faster_and_97_smaller_alternative/), but I'll use "just", so we don't have to have a discussion about utility libraries 😆.

2024-11-04 12:49 UTC, myieye commented
![image](https://github.com/user-attachments/assets/d6c23f80-61c5-41a9-b3b6-7a516dca12c7)
![image](https://github.com/user-attachments/assets/02b567f4-a284-495c-abd1-65cc1cb35b67)
![image](https://github.com/user-attachments/assets/85e4da8b-6c4f-413c-b0a3-0dce825f49d4)

2024-11-05 08:21 UTC, hahn-kev approved these changes

2024-11-05 08:42 UTC, myieye commented
### Merge activity

* **Nov 5, 3:42 AM EST**: [Graphite](https://app.graphite.dev/github/pr/sillsdev/languageforge-lexbox/1183) rebased this pull request as part of a merge.

2024-11-05 09:03 UTC, merged