Fix trace context lost when squashing and rethrowing GQL errors
sillsdev/languageforge-lexbox pull request #1191
Opened 2024-10-31 07:57 UTC by myieye

2024-10-31 07:57 UTC, myieye commented
* **#1191** <a href="https://app.graphite.dev/github/pr/sillsdev/languageforge-lexbox/1191?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @myieye and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-01 02:41 UTC, hahn-kev requested changes
when I use the sandbox GQL 500 I get this error in the console
```
Uncaught (in promise) Error: Object has already been traced (60abceb2db8c181adeba64eb41d328b0 vs 60abceb2db8c181adeba64eb41d328b0).
    TraceItError types.ts:27
    traceIt types.ts:33
    tryCopyTraceContext types.ts:51
    squashErrors gql-client.ts:305
    throwAnyUnexpectedErrors gql-client.ts:285
    queryStore gql-client.ts:203
    sync index.js:150
    unsubscribers index.js:164
    set index.js:56
    m queryStore.ts:185
    subscribe wonka.mjs:1068
    scan wonka.mjs:402
    switchMap wonka.mjs:591
    switchMap wonka.mjs:591
    applyInnerSource wonka.mjs:111
// ... etc
```

2024-11-04 10:40 UTC, myieye commented
@hahn-kev I'm not surprised that there's a problem now that you've encountered one. But, I can't reproduce it.
I expect it only happens when there's a network error. When I use the GQL 500 button I get a GQL error (`error.graphQLErrors`) not a network error (`error.networkError`). So, I'm not sure how you got this, but I'm pretty sure I fixed it.

2024-11-05 09:38 UTC, hahn-kev approved these changes

2024-11-05 11:11 UTC, merged