Validate WritingSystemIds on creation
sillsdev/languageforge-lexbox pull request #1230
Opened 2024-11-12 07:18 UTC by rmunn

Fix #984.

We now validate WritingSystemId records on creation and throw ArgumentException for any invalid writing system IDs. The special ID value "default" is allowed, all other writing system IDs must be considered valid by the SIL.WritingSystems validation logic.

2024-11-12 07:25 UTC, rmunn commented
Five failing unit tests when I run this locally:

* LcmCrdt.Tests.EntityCopyMethodTests.EntityCopyMethodShouldCopyAllFields - Invalid writing system ID "Web"
* LcmCrdt.Tests.DataModelSnapshotTests.VerifyIObjectWithIdsMatchAdapterGetObjectTypeName - Invalid writing system ID "Group"
* FwLiteProjectSync.Tests.UpdateDiffTests.ExampleSentenceDiffShouldUpdateAllFields - Invalid writing system ID "gz"
* FwLiteProjectSync.Tests.UpdateDiffTests.SenseDiffShouldUpdateAllFields - Invalid writing system ID "wb"
* FwLiteProjectSync.Tests.UpdateDiffTests.EntryDiffShouldUpdateAllFields - Invalid writing system ID "ez"

The three FwLiteProjectSync tests are failing because AutoFaker.Generate() is generating randomly-named writing system IDs, and we're no longer allowing that. We'll need to teach Generate() to pick writing system IDs randomly from an allowable list.

... And the two LcmCrdt tests are failing for the same reason: there's an AutoFaker.Generate() call in there, which needs to be taught how to pick valid writing system IDs.

2024-11-12 07:45 UTC, rmunn commented
Commit 30bdc0f0 fixes the three FwLiteProjectSync tests. But interestingly, the two failing LcmCrdt tests are still generating writing systems that are randomly-chosen English words, rather than two-letter codes. Something in those tests isn't calling AutoFaker.Generate correctly...

2024-11-12 07:50 UTC, rmunn commented
Commit 5d94a57c passes the MultiStringOverride to the two tests that were failing — but it's not being called correctly. So far I'm not sure why.

2024-11-12 07:52 UTC, rmunn commented
Kevin has asked for some explicit unit tests around writing system ID validation, especially making sure that custom audio writing systems are going to validate. So I'm removing the review request, and I'll bring it back when those tests are written.

2024-11-13 04:49 UTC, hahn-kev requested changes
looks good, I left a comment about reusing the language list from SIL.WritingSystems instead of hardcoding our own

2024-11-13 04:49 UTC, hahn-kev commented on backend/FwLite/MiniLcm.Tests/WritingSystemCodes.cs
> +    public static string[] ValidTwoLetterCodes = [
rather than hard-coding this can we use `StandardSubtags.RegisteredLanguages`?

2024-11-14 04:14 UTC, hahn-kev approved these changes

2024-11-15 03:35 UTC, merged