New API for downloading LDML files from projects that allow sharing WS data
sillsdev/languageforge-lexbox pull request #1309
Opened 2024-12-09 05:13 UTC by rmunn

Currently this adds a "ldmlzip" command to our hg command runner.

Will return 403 Forbidden if project does not allow sharing ws data with SLDR. Will also return same 403 Forbidden error code if project does not exist, to avoid possibly leaking project codes.

If project exists and allows data sharing, command will return a zipfile containing CachedSettings/WritingSystems/*.ldml from the tip revision.

Future plans: C# code will unzip the \*.ldml files into a directory by project ID, then zip up the whole thing for the API result. Then we'll create a job to delete the LDML directory four hours later, to clean up.

Ideally we'd be able to start streaming the output zip file as we receive data from each project, rather than waiting until all projects have been accessed and only then starting to stream the output zip. But we'll see.

2024-12-09 05:23 UTC, rmunn commented on hgweb/command-runner.sh
> +    if (chg -R /var/hg/repos/$first_char/$project_code cat -r tip CachedSettings/SharedSettings/LexiconSettings.plsx | grep '<WritingSystems' | grep 'addToSldr="true"'); then
Not a mismatch; we check one code path for permission, and if there are no ldml files then an empty zip is fine.

2024-12-09 05:36 UTC, rmunn commented
Unfortunately it looks as though we won't be able to use ZipArchive to add files to the output stream asynchronously as they come in: we'd probably run into [this issue](https://www.github.com/dotnet/runtime/issues/1560) where ZipArchive tries to write the end-of-zipfile directory synchronously when it's disposed, but Kestrel doesn't allow synchronous writes to its HTTP output stream. So we might have to extract everything, then send the zip file separately. Which means that the HTTP connection might time out, so it's possible we'll have to make two API endpoints, one to prepare the zip file and one to download it. Testing required.

2025-01-15 16:10 UTC, rmunn commented
Rebased on top of current develop since it's been a month since this was started, and a lot has changed on the develop branch in that time.

2025-01-15 20:12 UTC, rmunn commented
Now working; marking as ready for review. Not ready to merge yet, as there are several discussion items (marked with TODO comments) in this PR, such as what the permission structure should be. But it's tested and working.

To test locally, you'll need to get a project with `addToSldr="true"` in its writing system configuration. None of our default test projects have that, but you can add that with the following method:

- `kubectl --context=docker-desktop exec -it deploy/hg -- bash`
- Inside the container, `cd /var/hg/repos/s/sena-3` or `/e/elawa-dev-flex`
- `hg co tip` to populate the repo's working directory
- edit the `CachedSettings/SharedSettings/LexiconSettings.plsx` file
- change the `<WritingSystems>` line to `<WritingSystems addToSldr="true">`
- `hg commit -m "Add to SLDR"`
    - You might have to run `hg config --edit` to set your username
- `hg co null` to empty the working directory now that the commit is in the repo
- Exit kubectl, go to browser
- Go to http://localhost/api/project/getLdmlZip

If all went well, the zipfile should contain a folder named for a project ID at the root. If you get a 22-byte zip file that's empty, then something went wrong.

2025-01-16 06:24 UTC, hahn-kev requested changes
left a bunch of feedback, let me know if I missed any questions you still have.

One thought is to return 404 if there's no projects found, that should make it clear what's going on rather than an empty zip being an expected result.

2025-01-16 06:24 UTC, hahn-kev commented on backend/LexCore/ServiceInterfaces/IHgService.cs
> +    Task<System.IO.Compression.ZipArchive?> GetLdmlZip(ProjectCode code, CancellationToken token = default);
please add a using statement and change this to just `ZipArchive`

2025-01-16 06:24 UTC, hahn-kev commented on backend/LexBoxApi/Services/ProjectService.cs
> +        var path = System.IO.Path.Join(System.IO.Path.GetTempPath(), "ldml-zip"); // TODO: pick random name, rather than predictable one
import path also to simplify all the lines using Path

2025-01-16 06:24 UTC, hahn-kev commented on backend/LexBoxApi/Services/ProjectService.cs
> +        var zip = await hgService.GetLdmlZip(project.Code, token);
should be a using statement to dispose of the zip once this method returns

2025-01-16 06:24 UTC, hahn-kev commented on backend/LexBoxApi/Jobs/DeleteTempDirectoryJob.cs
> +        return Task.Run(() =>
this doesn't need to be wrapped in a task since it's not running as part of a web request

2025-01-16 06:24 UTC, hahn-kev commented on backend/LexBoxApi/Controllers/ProjectController.cs
> +        await Response.SendFileAsync(path, token);
if you return `File` then you don't need to handle status codes or content disposition manually. You'll have to change the return type of this method

2025-01-16 06:24 UTC, hahn-kev commented on backend/LexBoxApi/Controllers/ProjectController.cs
> +    [AdminRequired] // TODO: Decide on permissions, because we don't want everyone triggering this
admin only is a good choice, it won't be exposed in the UI so I'm not worried about our admins executing it

2025-01-16 06:24 UTC, hahn-kev commented on backend/LexBoxApi/Controllers/ProjectController.cs
> +    [HttpGet("getLdmlZip")] // TODO: Discuss endpoint name, and whether it should be GET or POST, at next opportunity
I think a GET is fine since it's not actually modifying data. maybe `sldr-export`?

2025-01-16 14:22 UTC, rmunn commented on backend/LexBoxApi/Services/ProjectService.cs
> +        var zip = await hgService.GetLdmlZip(project.Code, token);
Done in commit 3910173f.

2025-01-16 16:38 UTC, rmunn commented on backend/LexBoxApi/Jobs/DelayedLexJob.cs
> +            // TODO: Is there a simpler way of telling Quartz "Hey, enqueue this job after X delay"? Picking a unique trigger name each time seems unnecessarily complicated.
... Found it, finally. All the code examples called `.WithIdentity` on the trigger builder, but the [TriggerBuilder API docs](https://docs.quartz-scheduler.net/apidoc/3.0/html/199cc54a-30af-2168-5f4f-ded0e09f7b4c.htm) mention that if you don't call `.WithIdentity` it will create a random name for you. (I *do*, as far as I can tell, have to create a trigger if I want to schedule the job for X hours in the future; `scheduler.TriggerJob` is only for triggering the job immediately).

2025-01-16 17:11 UTC, rmunn commented on backend/LexBoxApi/Services/ProjectService.cs
> +        var zip = await hgService.GetLdmlZip(project.Code, token);
Done in commit bcc51cbc.

2025-01-16 17:12 UTC, rmunn commented on backend/LexBoxApi/Jobs/DelayedLexJob.cs
> +public abstract class DelayedLexJob() : LexJob
Removed in commit aed9d4f5.

2025-01-16 17:12 UTC, rmunn commented on backend/LexBoxApi/Jobs/DelayedLexJob.cs
> +            .StartAt(now.Add(delay))
Done in commit aed9d4f5. I used `TimeSpan.Duration()` to get the absolute value of the delay, so if someone accidentally passes in minus 4 hours then the job will fire 4 hours in the future.

2025-01-16 17:13 UTC, rmunn commented on backend/LexBoxApi/Jobs/DelayedLexJob.cs
> +            // TODO: Is there a simpler way of telling Quartz "Hey, enqueue this job after X delay"? Picking a unique trigger name each time seems unnecessarily complicated.
Done in commit aed9d4f5.

2025-01-16 17:17 UTC, rmunn commented on backend/LexBoxApi/Services/HgService.cs
> +    private async Task<HttpContent?> ExecuteHgCommandServerCommand_ErrorsOk(ProjectCode code, string command, IEnumerable<HttpStatusCode> okErrors, CancellationToken token)
I didn't want to change all 11 references to ExecuteHgCommandServerCommand to expect an `HttpContent?` instead of an `HttpContent` and have to check for null, so I simply renamed this method to MaybeExecuteHgCommandServerCommand and left it as a separate method.

Done in commit ffe3c5a6, but let me know if you want a different solution here.

2025-01-16 17:18 UTC, rmunn commented on backend/LexBoxApi/Jobs/DeleteTempDirectoryJob.cs
> +        return Task.Run(() =>
Done in commit 1e5e8169.

2025-01-16 18:51 UTC, rmunn commented on backend/LexBoxApi/Controllers/ProjectController.cs
> +        await Response.SendFileAsync(path, token);
Done in commit 72f1a52e.

2025-01-16 18:51 UTC, rmunn commented on backend/LexBoxApi/Controllers/ProjectController.cs
> +    [AdminRequired] // TODO: Decide on permissions, because we don't want everyone triggering this
TODO comment removed in commit 72f1a52e.

2025-01-16 18:52 UTC, rmunn commented on backend/LexBoxApi/Controllers/ProjectController.cs
> +    [HttpGet("getLdmlZip")] // TODO: Discuss endpoint name, and whether it should be GET or POST, at next opportunity
Done in commit 72f1a52e.

2025-01-16 19:19 UTC, rmunn commented
@hahn-kev wrote:
> left a bunch of feedback, let me know if I missed any questions you still have.
> 
> One thought is to return 404 if there's no projects found, that should make it clear what's going on rather than an empty zip being an expected result.

All comments addressed, and commit e7b98d8f sets it up to return 404 instead of an empty zip, as well as putting a UTC timestamp into the filename so that it's more obvious when the API call was run.

This is ready for re-review.

2025-01-17 02:54 UTC, hahn-kev approved these changes
looks good to me, one minor nitpick but feel free to merge this in

2025-01-17 02:54 UTC, hahn-kev commented on backend/LexBoxApi/Services/ProjectService.cs
> +        using var enumerator = Directory.EnumerateDirectories(zipRoot).GetEnumerator();
`Directory.EnumerateDirectories(zipRoot).Any()` will do the same thing you're doing here.

2025-01-17 14:46 UTC, merged