Fix i18n for emails
sillsdev/languageforge-lexbox pull request #535
Opened 2024-02-01 13:21 UTC by myieye

Resolves #534 

Init i18n for emails and send Accept-Language header to svelte when rendering emails

2024-02-02 09:20 UTC, hahn-kev requested changes
I didn't see a problem testing locally with English but maybe that's just the default.

2024-02-02 09:29 UTC, myieye commented on backend/LexBoxApi/Services/EmailService.cs
> +            new CreateProjectRequestEmail("Admin", new CreateProjectRequestUser(user.Name, user.Email), projectInput), user.Locale);
😆!! Good catch!!

2024-02-02 10:30 UTC, myieye commented on backend/LexBoxApi/Services/EmailService.cs
> +            new CreateProjectRequestEmail("Admin", new CreateProjectRequestUser(user.Name, user.Email), projectInput), user.Locale);
Fixed it

2024-02-02 10:31 UTC, myieye commented
This PR is now on hold. See #545.

2024-02-06 14:22 UTC, myieye commented
Will be covered in #545

2024-02-06 14:22 UTC, closed without merging