Better Typescript type in fixtures for executeGql
sillsdev/languageforge-lexbox pull request #573
Opened 2024-02-15 02:35 UTC by rmunn

Fix #570.

2024-02-15 08:00 UTC, myieye requested changes
@rmunn I realize now that...we should probably be using the same GQL-client that we use in our application code. Then we have generated types and type-safety out of the box.

2024-02-16 01:52 UTC, rmunn commented
> @rmunn I realize now that...we should probably be using the same GQL-client that we use in our application code. Then we have generated types and type-safety out of the box.

I don't think we can; it's too tied to Svelte, with stores and so on, while the Playwright tests run in a Node.JS environment. We might be able to pick it apart and separate out the stores from the client code, splitting src/lib/gql/gql-client.ts in two, but that's WAY out of scope for what was supposed to be a tiny PR.

2024-02-16 10:22 UTC, myieye approved these changes
Gotcha 👍

2024-02-16 13:46 UTC, hahn-kev approved these changes

2024-02-19 01:26 UTC, merged