Extract language tags from FLEx projects and store in DB metadata
sillsdev/languageforge-lexbox pull request #952
Opened 2024-07-11 09:12 UTC by rmunn

WIP. Will fix #922 when done.

So far this extracts language tags, but does nothing yet to validate or process them. That might come in a separate PR; this one might just store the language tag data into a JSON column and leave the analysis for later.

Currently I have sketched out a little bit of code that analyses the tags and tries to figure out the project language; that might be removed from this PR and put into a new PR once I flesh it out a little.

2024-07-12 09:14 UTC, rmunn commented on backend/LexData/Migrations/LexBoxDbContextModelSnapshot.cs
> +                                        .HasColumnType("uuid");
Why is this here? What actual DB column does it correspond to? I have no idea why EF does this.

2024-07-12 09:52 UTC, rmunn commented
Actually, now that I take another look at #922 this doesn't yet do everything the issue asks for. For example, there's no GraphQL filtering available yet. Marking as draft and removing review request for now.

2024-07-15 09:34 UTC, rmunn reviewed
Self-review finished. Marked a few places I'd like specific feedback on: e.g,, should I spend the time to do the proposed refactor, or is it readable enough already and I should move on to something else?

2024-07-16 07:36 UTC, hahn-kev requested changes
just some minor requests, including removing an empty migration

2024-07-16 07:36 UTC, hahn-kev commented on backend/LexBoxApi/Services/ProjectService.cs
> +        await dbContext.SaveChangesAsync();
I think in that case the caller can just call `IHgService.GetProjectIdOfFlexProject`

2024-07-18 03:53 UTC, rmunn commented on frontend/src/routes/(authenticated)/project/[project_code]/+page.svelte
> +    await invalidate(`project:${project.code}`);
Kevin and I decided to change this to a mutation, but in a separate PR so as not to expand the scope of the current PR too much. I opened https://github.com/sillsdev/languageforge-lexbox/issues/970 to track that work.

2024-07-18 04:01 UTC, rmunn commented on backend/LexBoxApi/Services/HgService.cs
> +        var curAnalysisWss = curAnalysisWssStr.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries);
Done in commit 27699a05.

2024-07-18 04:02 UTC, rmunn commented on backend/LexData/Migrations/20240715044054_AddIsDefaultFieldToFLExWsId.cs
Yeah, should be safe, Done in commit 3cbc6fda.

2024-07-18 04:02 UTC, rmunn commented on frontend/src/routes/(authenticated)/project/[project_code]/+page.svelte
> +              loading={loadingEntryCount}
Yep, bit of copy-and-paste laziness there. Fixed in commit 47117b4d.

2024-07-18 04:02 UTC, rmunn commented on frontend/src/routes/(authenticated)/project/[project_code]/+page.svelte
> +              loading={loadingEntryCount}
Fixed in commit 47117b4d.

2024-07-19 07:41 UTC, hahn-kev approved these changes
looks good to me

2024-07-23 02:06 UTC, merged