set project purpose on project page
sillsdev/languageforge-lexbox pull request #969
Opened 2024-07-17 08:53 UTC by psh0078

fixes #931.

2024-07-18 02:57 UTC, psh0078 commented
I am stuck on this error where modal becomes null when trying to be closed.

![Screenshot 2024-07-17 152827](https://github.com/user-attachments/assets/d330761d-a0fc-42b7-8cdc-a603bc0d4726)

2024-07-18 04:33 UTC, rmunn requested changes
Couple changes needed, then this should be good to go,

2024-07-18 04:33 UTC, rmunn commented on backend/LexBoxApi/GraphQL/ProjectMutations.cs
> +        projectService.InvalidateProjectConfidentialityCache(input.ProjectId);
The project confidentiality cache is not affected by the retention policy changing; this line can be removed.

2024-07-18 04:33 UTC, rmunn commented on frontend/src/routes/(authenticated)/project/create/+page.svelte
> +      <option value={RetentionPolicy.Unknown}>{'Unknown'}</option>
This should be removed once testing is complete.

2024-07-24 04:35 UTC, rmunn approved these changes
LGTM now. Good work.

2024-07-24 04:40 UTC, merged